export const data = [
    {
      question: "Who is the Father of the Computer?",
      option1: "Charles Babbage",
      option2: "Thomas Edison",
      option3: "Albert Einstein",
      option4: "Isaac Newton",
      ans: 1,
    },
    {
      question: "What do you call a person who uses the internet to explore and communicate?",
      option1: "Citizen",
      option2: "Resident",
      option3: "Cybernaut",
      option4: "None of the above",
      ans: 3,
    },
    {
      question: "Who invented Compact Disc?",
      option1: "James T. Russell",
      option2: "Fujio Masuoka",
      option3: "Thomas Edison",
      option4: "Martin Cooper",
      ans: 1,
    },
    {
      question: "What do you need to use to connect to the internet?",
      option1: "Mouse",
      option2: "Modem", 
      option3: "CPU",
      option4: "Keyboard",
      ans: 2,
    },
    {
      question: "How much is a byte equal to?",
      option1: "8 bits",
      option2: "16 bits",
      option3: "32 bits",
      option4: "64 bits",
      ans: 1,
    },
    {
      question: "Which device is required for the Internet connection?",
      option1: "Modem",
      option2: "Router",
      option3: "LAN Cable",
      option4: "Pen Drive",
      ans: 1,
    },
    {
      question: "Which continent has the highest number of countries?",
      option1: "Asia",
      option2: "Europe",
      option3: "North America",
      option4: "Africa",
      ans: 4,
    },
    {
      question: "Junk e-mail is also called?",
      option1: "Spam",
      option2: "Fake",
      option3: "Archived",
      option4: "Bin",
      ans: 1,
    },
    {
      question: "A computer cannot BOOT if it does not have the?",
      option1: "Application Software",
      option2: "Internet",
      option3: "Operating System",
      option4: "Mouse",
      ans: 3,
    },
    {
      question: "First page of Website is termed as?",
      option1: "Index Page",
      option2: "Homepage",
      option3: "Sitemap",
      option4: "Pen Drive",
      ans: 2,
    }
  ];